---
- name: polybar - install dependencies
  dnf: 
    name: 
      - cmake
      - "@development-tools"
      - gcc-c++ 
      - cairo-devel 
      - xcb-proto 
      - xcb-util-devel 
      - xcb-util-wm-devel 
      - xcb-util-image-devel
      - jsoncpp-devel
      - alsa-lib-devel
      - wireless-tools-devel
      - libmpdclient-devel
      - libcurl-devel
      - clang
    state: latest

- name: polybar - clone repo
  git:
    repo: https://github.com/jaagr/polybar
    dest: "{{ ansible_env.HOME }}/polybar"
    clone: true

- name: polybar - create build directory
  file: 
    path: "{{ ansible_env.HOME }}/polybar/build"
    state: directory

- name: polybar - make
  shell: cmake -DCMAKE_C_COMPILER="clang" -DCMAKE_CXX_COMPILER="clang++" .. 
  args:
    chdir: "{{ ansible_env.HOME }}/polybar/build"

- name: polybar - install
  shell: make install
  args:
    chdir: "{{ ansible_env.HOME }}/polybar/build"
