---
- name: virtualbox - install dependencies 
  dnf:
    name: 
      - gcc
      - kernel-devel
      - kernel-headers
      - dkms
      - make
      - bzip2
      - perl
    state: latest

- name: export KERN_DIR env variable
  shell: KERN_DIR=/usr/src/kernels/$(uname -r) && export KERN_DIR