---
- name: lightdm and slick greeter - install packages
  dnf:
    name: 
      - lightdm
      - slick-greeter
    state: latest

- name: lightdm - enable service
  systemd:
    name: lightdm
    enabled: yes

- name: slick greeter - enable
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#greeter-session=example-gtk-gnome'
    line: 'greeter-session=slick-greeter'
