---
- name: install common packages
  dnf:
    name: 
      - vim-enhanced
      - libselinux-python
      - rxvt-unicode
      - feh
      - ImageMagick 
      - neovim 
      - stow
      - neofetch
    state: latest
      
- name: install pywal
  pip:
    name: pywal
    executable: pip-3

- name: install vundle to vim
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: set folder permissions for vim
  file:
    path: "{{ ansible_env.HOME }}/.vim"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: install vundle to neovim
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.config/nvim/bundle/Vundle.vim"

- name: set folder permissions for config
  file:
    path: "{{ ansible_env.HOME }}/.config"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"