---
- name: install common packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim-enhanced
    - libselinux-python
    - rxvt-unicode
    - feh

- name: install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: Create config file
  copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    force: no
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
