---
- name: install common packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim-enhanced
    - libselinux-python
    - rxvt-unicode
    - feh
    - ImageMagick 
    - neovim 
      
- name: install pywal
  pip:
    name: pywal
    executable: pip-3

- name: install vundle to vim
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: install vundle to neovim
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ ansible_env.HOME }}/.config/nvim/bundle/Vundle.vim"
